# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4fa69135e2befd10976f0faedb4aa95598e0959e353c7c73574cef733b7036167f0182b89bb0e6980777c91d7c913d490b228f9eb79ffdcc80ee8c4f4115246

test:
  secret_key_base: 7d0cad9e77661a27ddf9903f8f454f2fa02a31524a1bbf78d2423a0de4bfe2a722aca78ba300733c1f6524619bc2a3ffc11cc320825d8baba7858c67f8480778

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
